name: Make Docs
on:
  push:
    paths:
      - 'docs/**'
  release:

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Doc Builder
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk

    - run: cd docs && make

    - uses: actions/upload-artifact@v2
      with:
        name: Team_Gold_Docs
        path: docs/_build/pdf/*.pdf
  
  make_instructions:
    runs-on: ubuntu-latest
    name: Instruction Builder
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk

    - name: Install requirements
      run: pip install -r docs/requirements.txt

    - run: cd docs && make latexpdf

    - run: mv docs/_build/latex/climatemonitoringsystem.pdf docs/_build/latex/tidalforceuniformandstyleguide.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: CMS_Instruction_Manual
        path: docs/_build/latex/tidalforceuniformandstyleguide.pdf
